### ISSUE TITLE
Dependency tree w/ differently cased dependencies conflicts

### ISSUE THREAD

**Issue by lluisgerard** [Zewo/PostgreSQL#11]
At some point, when trying to build this package, it clones https://github.com/SwiftX/C7.git and then clones https://github.com/open-swift/C7.git which causes a conflict.

This is a known bug here https://bugs.swift.org/browse/SR-1195 but I wonder how can anyone build it without having this issue.

My Package.swift:
```swift
import PackageDescription

let package = Package(
    dependencies: [
        .Package(url: "https://github.com/Zewo/PostgreSQL.git", majorVersion: 0, minor: 4)
    ]
)
```

When trying to build:
```bash
swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib/
```
```bash
Cloning https://github.com/Zewo/PostgreSQL.git
Resolved version: 0.4.1
Cloning https://github.com/Zewo/CLibpq-OSX.git
Resolved version: 0.4.0
Cloning https://github.com/Zewo/SQL.git
Resolved version: 0.4.2
Cloning https://github.com/Zewo/Data.git
Resolved version: 0.4.9
Cloning https://github.com/Zewo/OS.git
Resolved version: 0.4.2
Cloning https://github.com/SwiftX/C7.git
Resolved version: 0.2.0
Cloning https://github.com/Zewo/String.git
Resolved version: 0.4.3
Cloning https://github.com/Zewo/Log.git
Resolved version: 0.4.5
Cloning https://github.com/VeniceX/File.git
Resolved version: 0.4.3
Cloning https://github.com/VeniceX/Venice.git
Resolved version: 0.4.2
Cloning https://github.com/VeniceX/CLibvenice.git
Resolved version: 0.4.2
Cloning https://github.com/open-swift/C7.git
/usr/bin/git clone --recursive --depth 10 https://github.com/open-swift/C7.git /Users/lluisgerard/Xcode/apps/APP/Packages/C7
fatal: destination path '/Users/lluisgerard/Xcode/apps/APP/Packages/C7' already exists and is not an empty directory.

error: Failed to clone https://github.com/open-swift/C7.git to /Users/lluisgerard/Xcode/apps/APP/Packages/C7
```

Cheers

**Comment by antonmes** [comment]
0.4 is dead release because of this conflicts, please use `minor: 5`.
it happens because Data depends on C7 `0.2.0` and some other package depends on higher version. 
also you could try manually change C7 version in `Data` or some other modules.

**Comment by lluisgerard** [comment]
With `minor: 5` I'm getting another error specifically related to the SPM so closing it.

```error: NoSources("/Users/lluisgerard/Xcode/apps/APP/APP.xcworkspace")```

And I've got:
```
Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 9f0d189820, Swift 1c720b8f84)
Target: x86_64-apple-macosx10.9
```

**Comment by lluisgerard** [comment]
Just as a note for the future. It seems that SPM is meant to be used without Xcode.

Found this related article just in case somebody tries to do the same and gets to this issue http://cjwirth.com/2016/03/07/using-xcode-and-spm-together/

**Comment by antonmes** [comment]
the latest vesrions of swiftpm can generate xcode project for you, just add `-X` at the end of build command: `swift build -X` for simple project, and
`swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib/ -X` to have linker flags automatically added to the xcode build settings

**Comment by antonmes** [comment]
i couldn't build 0.5 with the 04.12 snapshot though, thats weird. i'll look into this issue later.

**Comment by antonmes** [comment]
the package was updated and now compiles with the 05-09 developer snapshot 🎉
