### ISSUE TITLE
Build with error: library not found for -lvenice for architecture x86_64

### ISSUE THREAD

**Issue by ipconfiger** [Zewo/PostgreSQL#6]
ld: library not found for -lvenice for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain/usr/bin/swift-build-tool -f /Users/liming/workspace/swift_proj/test00/.build/debug.yaml default -v

**Comment by antonmes** [comment]
try `swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib/`
but some 0.3 packages are not compatible with toolchains after 2016-02-08
