### ISSUE TITLE
Packet Manager issue Ubuntu 15.10

### ISSUE THREAD

**Issue by richzertuche** [Zewo/PostgreSQL#7]
When running `swift-build` or `swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib/`:

error: NoSources("/SwiftExpress/Packages/CLibvenice-0.4.0/Sources/include")

Been trying to find a way to fix it, but haven't been able yet :/

**Comment by Danappelxx** [comment]
Which snapshot are you using? If you're _not_ using the last one, you should have the minor version set to 3 (from what I can tell it's at 4).

**Comment by antonmes** [comment]
seems like PosgreSQL is broken, will fix it in an hour/two.
you can use 0.3 version with Feb 8 toolchains.

**Comment by richzertuche** [comment]
@Danappelxx using the March 16, 2016 Development Snapshot

@antonmes so use the Ubuntu 15.10 Swift Development Snapshot from Feb 8 and try with:
`.Package(url: "https://github.com/Zewo/PostgreSQL.git", majorVersion: 0, minor: 3)`
right?

Thanks both! I'll try again later today with Feb 8 minor 3 and with the lastest fix also and let you know how it went.
